# Generated by Django 5.2.8 on 2025-11-26 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sport name')),
                ('slug', models.SlugField(help_text='URL', unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='sports/icons', verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tag name')),
                ('slug', models.SlugField(help_text='URL', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Team name')),
                ('short_name', models.CharField(blank=True, max_length=200, verbose_name='Team short name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos', verbose_name='Logo')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='City')),
                ('slug', models.SlugField(help_text='URL', unique=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sports.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Game start time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='scheduled', max_length=200, verbose_name='Status')),
                ('score_home', models.PositiveIntegerField(blank=True, null=True, verbose_name='Home score')),
                ('score_away', models.PositiveIntegerField(blank=True, null=True, verbose_name='Away score')),
                ('broadcast_url', models.URLField(blank=True, verbose_name='Broadcast URL')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='sports.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='sports.team')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Athlete first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Athlete last name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='athletes/', verbose_name='Photo')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Position')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sports.team')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='URL', unique=True)),
                ('content', models.TextField(blank=True, verbose_name='Article content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Article creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Article update time')),
                ('is_published', models.BooleanField(default=True, verbose_name='Article published')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Preview image')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_athletes', models.ManyToManyField(blank=True, related_name='news', to='sports.athlete')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='sports.match')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='sports.tag')),
                ('related_teams', models.ManyToManyField(blank=True, related_name='news', to='sports.team')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tournament name')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Current season')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='sports.sport')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sports.tournament'),
        ),
    ]
